name: Manually Created Docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build docs
      run: touch .nojekyll
        && cp _build/html/* .
