name: Manually Created Docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: apt install -y doxygen
        && pip3 install sphinx-doc
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
    - name: Build docs
      run: cd docs
        && make html
        && cp _build/html/* .
        && cd _build/html
        && touch .nojekyll
