name: Manually Created Docs

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Requirements
      run: apt install -y doxygen
        && pip3 install sphinx-doc
        && pip3 install sphinx-rtd-theme
        && pip3 install breathe
    - name: Checkout repo
      uses: actions/checkout@1.0.0
    - name: Build docs
      run: cd docs
        && make html
        && cp _build/html/* .
        && cd _build/html
        && touch .nojekyll
    - name: Deploy
      uses: ceyhunsen/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs_sphinx/_build/html # The folder the action should deploy.
